# Generated by Codex on 2026-07-17

import django.db.models.deletion
from django.db import migrations, models


def set_existing_share_actor(apps, _schema_editor):
    task_share = apps.get_model("sharing", "TaskShare")
    for share in task_share.objects.select_related("task"):
        share.shared_by_id = share.task.owner_id
        share.save(update_fields=["shared_by"])


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
        ("sharing", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="taskshare",
            name="shared_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sent_shares",
                to="accounts.useraccount",
            ),
        ),
        migrations.AddField(
            model_name="taskshare",
            name="responded_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.RunPython(set_existing_share_actor, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="taskshare",
            name="shared_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sent_shares",
                to="accounts.useraccount",
            ),
        ),
    ]
